config/routes.rb
Rails.application.routes.draw do
  resources :organizations, only: [:new, :show, :create]
  root 'organizations#new'
  get '*unmatched_route', to: 'application#not_found'
end

app/models/language.rb
class Language < ActiveRecord::Base
  belongs_to :member
  validates :name, presence: true
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_and_belongs_to_many :organizations
  has_many :languages

  def set_github_attrs(member_info)
    self.github_login = member_info[:login]
    self.github_id = member_info[:id]
    self.avatar_url = member_info[:avatar_url]
    self.profile_url = member_info[:html_url]
    self.last_fetched_at = Time.zone.now
  end

  def stale?
    Time.zone.now.to_i - updated_at.to_i > 30.seconds.to_i
  end
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_and_belongs_to_many :members
  validates :name, presence: true

  def set_github_attrs(org_info)
    return false if org_info == false
    self.login = org_info[:login]
    self.github_id = org_info[:id]
    self.avatar_url = org_info[:avatar_url]
    self.html_url = org_info[:html_url]
    self.last_fetched_at = Time.zone.now
  end

  def stale?
    Time.zone.now.to_i - updated_at.to_i > 1.minute.to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found
    flash[:alert] = "Sorry. We could not find what you're looking for."
    redirect_to root_path
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # POST /organizations
  def create
    org_name = params[:organization][:name].downcase
    if org_name.blank?
      flash[:alert] = 'You must provide an organization name.'
      redirect_to root_path
      return
    end
    @organization = Organization.find_or_initialize_by(name: org_name)
    @client = GithubClient.new
    if @organization.new_record? || @organization.stale?
      data = @client.fetch_org_info(@organization.name)
      if @organization.set_github_attrs(data)
        if @organization.save
          grab_members(@organization)
          flash[:notice] = "We're busy gathering data from GitHub." \
                           ' This might take a while. You may want to' \
                           ' refresh often.'
          redirect_to @organization
        else
          flash[:alert] = 'Failed to create organization: ' +
                          @organization.errors.full_messages.join(', ')
          redirect_to root_path
        end
      else
        not_found
      end
    else
      redirect_to @organization
    end
  end

  # GET /organizations/1
  # GET /organizations/openlexington
  def show
    @organization = Organization.friendly.find(params[:id])
    if params[:sort]
      @members = @organization.members.includes(:languages).
                 order("languages.name = \'#{params[:sort]}\' DESC,
                                     languages.bytes DESC")
    else
      @members = @organization.members.order('github_login')
    end
  rescue ActiveRecord::RecordNotFound
    not_found
  end

  private

  def not_found
    flash[:alert] = 'Sorry. We could not find that organization on GitHub.'
    redirect_to root_path
  end

  def grab_members(org)
    @client = GithubClient.new
    @members = @client.fetch_org_member_list(org.login)
    @members.each do |member_data|
      member_args = { github_login: member_data.login }
      member = Member.find_or_initialize_by(member_args)
      next unless member.new_record? || member.stale?
      member.set_github_attrs(member_data)
      member.organizations << org unless member.organizations.exists?(org.id)
      member.save
      SkillFetcherJob.perform_later(member.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice('alert', 'error', 'notice', 'success')
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_github_badge.html.erb
<a href="https://github.com/chaserx/wheelhouse" class="github-corner"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render 'github_badge' %>
  <div class="wrapper">
    <div class='center text-center text-big'>
      <h1>
        <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu"><i class="fa fa-code-fork"></i> GitLingo</a>
      </h1>
    </div>
    <%= render "flashes" -%>
    <%= yield %>
  </div>
  <%= render "javascript" %>
</body>
</html>

app/views/organizations/new.html.haml
.center
  %h2{style: 'text-align: center'} What programming languages are in your wheelhouse?

  = simple_form_for @organization, html: {class: 'search-bar', role: 'search'} do |f|
    = f.error_notification
    = f.search_field :name, placeholder: 'GitHub Organization Name'
    = button_tag(data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Searching...".html_safe}) do
      %i.fa.fa-search

app/views/organizations/show.html.haml
.center
  .org-info
    = image_tag @organization.avatar_url, class: 'org_avatar'
    = @organization.name
    public members' wheelhouse
  - if @members.any?
    - @members.each do |member|
      .member
        .member-image
          = image_tag member.avatar_url, class: 'org_avatar'
        .member-content
          %h1= link_to member.github_login, member.profile_url
          .member-detail
            %p
              - if member.languages.any?
                - member.languages.each_with_index do |language, index|
                  = link_to language.name.to_s.downcase, organization_path(@organization, sort: language.name), class: "lang rank-#{index}"
              - else
                %i.fa.fa-cog.fa-spin
                Gathering language data. Please stand by.
  - else
    %p There are no public members for this organization.